version: "2"
checks:
  similar-code:
    config:
      threshold: 150
  identical-code:
    config:
      threshold: 150

exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
- "/utils/scripts/"
- "**/dependencyinjection/"
